# To use this file, insall the REST Client extension
# vscode:extension/humao.rest-client

# To switch environments:
#  - Ctrl+Alt+E(Cmd+Alt+E for macOS)
#  - Or `Rest Client: Switch Environment` from command palette

# You'll need to switch to either `local` or `vercel` to get started.

@baseUrl = {{host}}/api/

GET {{baseUrl}}
###


# @name GetRecipe

GET {{baseUrl}}meal/Hamburgers
###


# @name CreateRecipe

POST {{baseUrl}}meal
Content-Type: application/json

{
   "category": "vegetarian",
   "meal": "eggs",
   "ingredientList":[
      {
         "items1": "eggs",
         "items2": "cheese",
         "items3": "salt",
         "items4": "pepper"
      }
   ],
   "measurement":[
      {
         "size1": "1/4 cup cheese",
         "size2": "2 eggs",
         "size3": "1/2 teaspoon salt",
         "size4": "1 teaspoon Pepper"
      }
   ],
   "vegetarian": true,
   "instructions": "Boil",
   "userName": "Me"
}
###


# @name UpdateRecipe

PATCH  {{baseUrl}}meal/63f90698375313e609007af1
Content-Type: application/json

{
   "category": "test",
   "meal": "Test Meal",
   "ingredientList":[
      {
         "items1": "chicken",
         "items2": "flour"
      }
   ],
   "measurement":[
      {
         "size1": "4 chickens",
         "size2": "3 cups"
      }
   ],
   "vegetarian": false,
   "instructions": "Fry twice",
   "userName": "Jas"
}
###


# @name DeleteRecipe
DELETE {{baseUrl}}meal/63f9076583ecaf05abb837d2
###
