# To use this file, insall the REST Client extension
# vscode:extension/humao.rest-client

# To switch environments:
#  - Ctrl+Alt+E(Cmd+Alt+E for macOS)
#  - Or `Rest Client: Switch Environment` from command palette

# You'll need to switch to either `local` or `vercel` to get started.

@baseUrl = {{host}}/api/

GET {{baseUrl}}
###


# @name GetRecipe

GET {{baseUrl}}meal/Oven Baked Chicken
###


# @name CreateRecipe

POST {{baseUrl}}meal
Content-Type: application/json

{
   "category": "Vegetarian",
   "meal": "Rice",
   "ingredientList":[
      {
         "items1": "rice"
      }
   ],
   "measurement":[
      {
         "size1": "1 cup"
      }
   ],
   "vegetarian": true,
   "instructions": "Boil",
   "userName": "Me"
}
###


# @name UpdateRecipe

PATCH  {{baseUrl}}meal/63f8fd934c5b2147cb7df5f9
Content-Type: application/json

{
   "category": "test",
   "meal": "Test Meal",
   "ingredientList":[
      {
         "items1": "chicken",
         "items2": "flour"
      }
   ],
   "measurement":[
      {
         "size1": "4 chickens",
         "size2": "3 cups"
      }
   ],
   "vegetarian": false,
   "instructions": "Fry twice",
   "userName": "Jas"
}
###


# @name DeleteRecipe
DELETE {{baseUrl}}meal/63f8fd934c5b2147cb7df5f9
###
