# To use this file, insall the REST Client extension
# vscode:extension/humao.rest-client

# To switch environments:
#  - Ctrl+Alt+E(Cmd+Alt+E for macOS)
#  - Or `Rest Client: Switch Environment` from command palette

# You'll need to switch to either `local` or `vercel` to get started.

@baseUrl = {{host}}/api/

GET {{baseUrl}}
###


# @name GetRecipe

GET {{baseUrl}}meal/Oven Baked Chicken
###


# @name CreateRecipe

POST {{baseUrl}}meal 
Content-Type: application/json

{
   "category": "Vegetarian",
   "meal": "Rice",
   "ingredientList":[
      {
         "item": "rice"
      }
   ],
   "measurement":[
      {
         "size": "1 cup"
      }
   ],
   "vegetarian": true,
   "instructions": "Boil",
   "userName": "Me"
}
###


# @name UpdateRecipe

PATCH  {{baseUrl}}meal/63f7c8543dc311a1566a6356
Content-Type: application/json

{
   "category": "Chicken",
   "meal": "Deep Fried Chicken",
   "ingredientList":[
      {
         "item": "chicken",
         "item": "flour"
      }
   ],
   "measurement":[
      {
         "size": "4 chickens",
         "size": "3 cups"
      }
   ],
   "vegetarian": false,
   "instructions": "Fry twice",
   "userName": "Jas"
}
###


# @name DeleteRecipe
DELETE {{baseUrl}}meal/63f7c8543dc311a1566a635b
###
